// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/loginattempt"
	"github.com/identity-platform/internal/ent/predicate"
)

// LoginAttemptUpdate is the builder for updating LoginAttempt entities.
type LoginAttemptUpdate struct {
	config
	hooks    []Hook
	mutation *LoginAttemptMutation
}

// Where appends a list predicates to the LoginAttemptUpdate builder.
func (_u *LoginAttemptUpdate) Where(ps ...predicate.LoginAttempt) *LoginAttemptUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetEmail sets the "email" field.
func (_u *LoginAttemptUpdate) SetEmail(v string) *LoginAttemptUpdate {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *LoginAttemptUpdate) SetNillableEmail(v *string) *LoginAttemptUpdate {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LoginAttemptUpdate) SetUserID(v uuid.UUID) *LoginAttemptUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LoginAttemptUpdate) SetNillableUserID(v *uuid.UUID) *LoginAttemptUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LoginAttemptUpdate) ClearUserID() *LoginAttemptUpdate {
	_u.mutation.ClearUserID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *LoginAttemptUpdate) SetIPAddress(v string) *LoginAttemptUpdate {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *LoginAttemptUpdate) SetNillableIPAddress(v *string) *LoginAttemptUpdate {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *LoginAttemptUpdate) ClearIPAddress() *LoginAttemptUpdate {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginAttemptUpdate) SetSuccess(v bool) *LoginAttemptUpdate {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginAttemptUpdate) SetNillableSuccess(v *bool) *LoginAttemptUpdate {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *LoginAttemptUpdate) SetFailureReason(v string) *LoginAttemptUpdate {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *LoginAttemptUpdate) SetNillableFailureReason(v *string) *LoginAttemptUpdate {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *LoginAttemptUpdate) ClearFailureReason() *LoginAttemptUpdate {
	_u.mutation.ClearFailureReason()
	return _u
}

// Mutation returns the LoginAttemptMutation object of the builder.
func (_u *LoginAttemptUpdate) Mutation() *LoginAttemptMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LoginAttemptUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAttemptUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LoginAttemptUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAttemptUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginAttemptUpdate) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := loginattempt.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "LoginAttempt.email": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginAttemptUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginattempt.Table, loginattempt.Columns, sqlgraph.NewFieldSpec(loginattempt.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(loginattempt.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(loginattempt.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(loginattempt.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(loginattempt.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(loginattempt.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginattempt.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(loginattempt.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(loginattempt.FieldFailureReason, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LoginAttemptUpdateOne is the builder for updating a single LoginAttempt entity.
type LoginAttemptUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *LoginAttemptMutation
}

// SetEmail sets the "email" field.
func (_u *LoginAttemptUpdateOne) SetEmail(v string) *LoginAttemptUpdateOne {
	_u.mutation.SetEmail(v)
	return _u
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_u *LoginAttemptUpdateOne) SetNillableEmail(v *string) *LoginAttemptUpdateOne {
	if v != nil {
		_u.SetEmail(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *LoginAttemptUpdateOne) SetUserID(v uuid.UUID) *LoginAttemptUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *LoginAttemptUpdateOne) SetNillableUserID(v *uuid.UUID) *LoginAttemptUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// ClearUserID clears the value of the "user_id" field.
func (_u *LoginAttemptUpdateOne) ClearUserID() *LoginAttemptUpdateOne {
	_u.mutation.ClearUserID()
	return _u
}

// SetIPAddress sets the "ip_address" field.
func (_u *LoginAttemptUpdateOne) SetIPAddress(v string) *LoginAttemptUpdateOne {
	_u.mutation.SetIPAddress(v)
	return _u
}

// SetNillableIPAddress sets the "ip_address" field if the given value is not nil.
func (_u *LoginAttemptUpdateOne) SetNillableIPAddress(v *string) *LoginAttemptUpdateOne {
	if v != nil {
		_u.SetIPAddress(*v)
	}
	return _u
}

// ClearIPAddress clears the value of the "ip_address" field.
func (_u *LoginAttemptUpdateOne) ClearIPAddress() *LoginAttemptUpdateOne {
	_u.mutation.ClearIPAddress()
	return _u
}

// SetSuccess sets the "success" field.
func (_u *LoginAttemptUpdateOne) SetSuccess(v bool) *LoginAttemptUpdateOne {
	_u.mutation.SetSuccess(v)
	return _u
}

// SetNillableSuccess sets the "success" field if the given value is not nil.
func (_u *LoginAttemptUpdateOne) SetNillableSuccess(v *bool) *LoginAttemptUpdateOne {
	if v != nil {
		_u.SetSuccess(*v)
	}
	return _u
}

// SetFailureReason sets the "failure_reason" field.
func (_u *LoginAttemptUpdateOne) SetFailureReason(v string) *LoginAttemptUpdateOne {
	_u.mutation.SetFailureReason(v)
	return _u
}

// SetNillableFailureReason sets the "failure_reason" field if the given value is not nil.
func (_u *LoginAttemptUpdateOne) SetNillableFailureReason(v *string) *LoginAttemptUpdateOne {
	if v != nil {
		_u.SetFailureReason(*v)
	}
	return _u
}

// ClearFailureReason clears the value of the "failure_reason" field.
func (_u *LoginAttemptUpdateOne) ClearFailureReason() *LoginAttemptUpdateOne {
	_u.mutation.ClearFailureReason()
	return _u
}

// Mutation returns the LoginAttemptMutation object of the builder.
func (_u *LoginAttemptUpdateOne) Mutation() *LoginAttemptMutation {
	return _u.mutation
}

// Where appends a list predicates to the LoginAttemptUpdate builder.
func (_u *LoginAttemptUpdateOne) Where(ps ...predicate.LoginAttempt) *LoginAttemptUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LoginAttemptUpdateOne) Select(field string, fields ...string) *LoginAttemptUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated LoginAttempt entity.
func (_u *LoginAttemptUpdateOne) Save(ctx context.Context) (*LoginAttempt, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LoginAttemptUpdateOne) SaveX(ctx context.Context) *LoginAttempt {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LoginAttemptUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LoginAttemptUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LoginAttemptUpdateOne) check() error {
	if v, ok := _u.mutation.Email(); ok {
		if err := loginattempt.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "LoginAttempt.email": %w`, err)}
		}
	}
	return nil
}

func (_u *LoginAttemptUpdateOne) sqlSave(ctx context.Context) (_node *LoginAttempt, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(loginattempt.Table, loginattempt.Columns, sqlgraph.NewFieldSpec(loginattempt.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "LoginAttempt.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, loginattempt.FieldID)
		for _, f := range fields {
			if !loginattempt.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != loginattempt.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Email(); ok {
		_spec.SetField(loginattempt.FieldEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(loginattempt.FieldUserID, field.TypeUUID, value)
	}
	if _u.mutation.UserIDCleared() {
		_spec.ClearField(loginattempt.FieldUserID, field.TypeUUID)
	}
	if value, ok := _u.mutation.IPAddress(); ok {
		_spec.SetField(loginattempt.FieldIPAddress, field.TypeString, value)
	}
	if _u.mutation.IPAddressCleared() {
		_spec.ClearField(loginattempt.FieldIPAddress, field.TypeString)
	}
	if value, ok := _u.mutation.Success(); ok {
		_spec.SetField(loginattempt.FieldSuccess, field.TypeBool, value)
	}
	if value, ok := _u.mutation.FailureReason(); ok {
		_spec.SetField(loginattempt.FieldFailureReason, field.TypeString, value)
	}
	if _u.mutation.FailureReasonCleared() {
		_spec.ClearField(loginattempt.FieldFailureReason, field.TypeString)
	}
	_node = &LoginAttempt{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{loginattempt.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
