// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/oauthclient"
	"github.com/identity-platform/internal/ent/oauthconsent"
	"github.com/identity-platform/internal/ent/oauthredirecturi"
)

// OAuthClientCreate is the builder for creating a OAuthClient entity.
type OAuthClientCreate struct {
	config
	mutation *OAuthClientMutation
	hooks    []Hook
}

// SetClientID sets the "client_id" field.
func (_c *OAuthClientCreate) SetClientID(v string) *OAuthClientCreate {
	_c.mutation.SetClientID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *OAuthClientCreate) SetName(v string) *OAuthClientCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetDescription sets the "description" field.
func (_c *OAuthClientCreate) SetDescription(v string) *OAuthClientCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableDescription(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetClientType sets the "client_type" field.
func (_c *OAuthClientCreate) SetClientType(v oauthclient.ClientType) *OAuthClientCreate {
	_c.mutation.SetClientType(v)
	return _c
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableClientType(v *oauthclient.ClientType) *OAuthClientCreate {
	if v != nil {
		_c.SetClientType(*v)
	}
	return _c
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_c *OAuthClientCreate) SetClientSecretHash(v string) *OAuthClientCreate {
	_c.mutation.SetClientSecretHash(v)
	return _c
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableClientSecretHash(v *string) *OAuthClientCreate {
	if v != nil {
		_c.SetClientSecretHash(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *OAuthClientCreate) SetStatus(v oauthclient.Status) *OAuthClientCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableStatus(v *oauthclient.Status) *OAuthClientCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedBy sets the "created_by" field.
func (_c *OAuthClientCreate) SetCreatedBy(v uuid.UUID) *OAuthClientCreate {
	_c.mutation.SetCreatedBy(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *OAuthClientCreate) SetCreatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableCreatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *OAuthClientCreate) SetUpdatedAt(v time.Time) *OAuthClientCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableUpdatedAt(v *time.Time) *OAuthClientCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OAuthClientCreate) SetID(v uuid.UUID) *OAuthClientCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OAuthClientCreate) SetNillableID(v *uuid.UUID) *OAuthClientCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddRedirectURIIDs adds the "redirect_uris" edge to the OAuthRedirectURI entity by IDs.
func (_c *OAuthClientCreate) AddRedirectURIIDs(ids ...uuid.UUID) *OAuthClientCreate {
	_c.mutation.AddRedirectURIIDs(ids...)
	return _c
}

// AddRedirectUris adds the "redirect_uris" edges to the OAuthRedirectURI entity.
func (_c *OAuthClientCreate) AddRedirectUris(v ...*OAuthRedirectURI) *OAuthClientCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddRedirectURIIDs(ids...)
}

// AddConsentIDs adds the "consents" edge to the OAuthConsent entity by IDs.
func (_c *OAuthClientCreate) AddConsentIDs(ids ...uuid.UUID) *OAuthClientCreate {
	_c.mutation.AddConsentIDs(ids...)
	return _c
}

// AddConsents adds the "consents" edges to the OAuthConsent entity.
func (_c *OAuthClientCreate) AddConsents(v ...*OAuthConsent) *OAuthClientCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddConsentIDs(ids...)
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_c *OAuthClientCreate) Mutation() *OAuthClientMutation {
	return _c.mutation
}

// Save creates the OAuthClient in the database.
func (_c *OAuthClientCreate) Save(ctx context.Context) (*OAuthClient, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OAuthClientCreate) SaveX(ctx context.Context) *OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OAuthClientCreate) defaults() {
	if _, ok := _c.mutation.ClientType(); !ok {
		v := oauthclient.DefaultClientType
		_c.mutation.SetClientType(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := oauthclient.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := oauthclient.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := oauthclient.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := oauthclient.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OAuthClientCreate) check() error {
	if _, ok := _c.mutation.ClientID(); !ok {
		return &ValidationError{Name: "client_id", err: errors.New(`ent: missing required field "OAuthClient.client_id"`)}
	}
	if v, ok := _c.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "OAuthClient.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ClientType(); !ok {
		return &ValidationError{Name: "client_type", err: errors.New(`ent: missing required field "OAuthClient.client_type"`)}
	}
	if v, ok := _c.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OAuthClient.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := oauthclient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedBy(); !ok {
		return &ValidationError{Name: "created_by", err: errors.New(`ent: missing required field "OAuthClient.created_by"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "OAuthClient.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "OAuthClient.updated_at"`)}
	}
	return nil
}

func (_c *OAuthClientCreate) sqlSave(ctx context.Context) (*OAuthClient, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OAuthClientCreate) createSpec() (*OAuthClient, *sqlgraph.CreateSpec) {
	var (
		_node = &OAuthClient{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(oauthclient.Table, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
		_node.ClientID = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(oauthclient.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeEnum, value)
		_node.ClientType = value
	}
	if value, ok := _c.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
		_node.ClientSecretHash = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(oauthclient.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedBy(); ok {
		_spec.SetField(oauthclient.FieldCreatedBy, field.TypeUUID, value)
		_node.CreatedBy = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(oauthclient.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.RedirectUrisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ConsentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OAuthClientCreateBulk is the builder for creating many OAuthClient entities in bulk.
type OAuthClientCreateBulk struct {
	config
	err      error
	builders []*OAuthClientCreate
}

// Save creates the OAuthClient entities in the database.
func (_c *OAuthClientCreateBulk) Save(ctx context.Context) ([]*OAuthClient, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OAuthClient, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OAuthClientMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) SaveX(ctx context.Context) []*OAuthClient {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OAuthClientCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OAuthClientCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
