// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/organization"
	"github.com/identity-platform/internal/ent/organizationmember"
	"github.com/identity-platform/internal/ent/predicate"
)

// OrganizationUpdate is the builder for updating Organization entities.
type OrganizationUpdate struct {
	config
	hooks    []Hook
	mutation *OrganizationMutation
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (_u *OrganizationUpdate) Where(ps ...predicate.Organization) *OrganizationUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetName sets the "name" field.
func (_u *OrganizationUpdate) SetName(v string) *OrganizationUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableName(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *OrganizationUpdate) SetSlug(v string) *OrganizationUpdate {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableSlug(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OrganizationUpdate) SetDescription(v string) *OrganizationUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDescription(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *OrganizationUpdate) ClearDescription() *OrganizationUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *OrganizationUpdate) SetDomain(v string) *OrganizationUpdate {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDomain(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *OrganizationUpdate) ClearDomain() *OrganizationUpdate {
	_u.mutation.ClearDomain()
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *OrganizationUpdate) SetLogoURL(v string) *OrganizationUpdate {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableLogoURL(v *string) *OrganizationUpdate {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *OrganizationUpdate) ClearLogoURL() *OrganizationUpdate {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *OrganizationUpdate) SetOwnerID(v uuid.UUID) *OrganizationUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableOwnerID(v *uuid.UUID) *OrganizationUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrganizationUpdate) SetStatus(v organization.Status) *OrganizationUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableStatus(v *organization.Status) *OrganizationUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationUpdate) SetUpdatedAt(v time.Time) *OrganizationUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrganizationUpdate) SetDeletedAt(v time.Time) *OrganizationUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrganizationUpdate) SetNillableDeletedAt(v *time.Time) *OrganizationUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrganizationUpdate) ClearDeletedAt() *OrganizationUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddMemberIDs adds the "members" edge to the OrganizationMember entity by IDs.
func (_u *OrganizationUpdate) AddMemberIDs(ids ...uuid.UUID) *OrganizationUpdate {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdate) AddMembers(v ...*OrganizationMember) *OrganizationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_u *OrganizationUpdate) Mutation() *OrganizationMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdate) ClearMembers() *OrganizationUpdate {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to OrganizationMember entities by IDs.
func (_u *OrganizationUpdate) RemoveMemberIDs(ids ...uuid.UUID) *OrganizationUpdate {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to OrganizationMember entities.
func (_u *OrganizationUpdate) RemoveMembers(v ...*OrganizationMember) *OrganizationUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OrganizationUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OrganizationUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := organization.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Organization.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := organization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Organization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(organization.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(organization.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(organization.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(organization.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(organization.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(organization.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(organization.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(organization.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(organization.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(organization.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(organization.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OrganizationUpdateOne is the builder for updating a single Organization entity.
type OrganizationUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OrganizationMutation
}

// SetName sets the "name" field.
func (_u *OrganizationUpdateOne) SetName(v string) *OrganizationUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableName(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetSlug sets the "slug" field.
func (_u *OrganizationUpdateOne) SetSlug(v string) *OrganizationUpdateOne {
	_u.mutation.SetSlug(v)
	return _u
}

// SetNillableSlug sets the "slug" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableSlug(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetSlug(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OrganizationUpdateOne) SetDescription(v string) *OrganizationUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDescription(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *OrganizationUpdateOne) ClearDescription() *OrganizationUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetDomain sets the "domain" field.
func (_u *OrganizationUpdateOne) SetDomain(v string) *OrganizationUpdateOne {
	_u.mutation.SetDomain(v)
	return _u
}

// SetNillableDomain sets the "domain" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDomain(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDomain(*v)
	}
	return _u
}

// ClearDomain clears the value of the "domain" field.
func (_u *OrganizationUpdateOne) ClearDomain() *OrganizationUpdateOne {
	_u.mutation.ClearDomain()
	return _u
}

// SetLogoURL sets the "logo_url" field.
func (_u *OrganizationUpdateOne) SetLogoURL(v string) *OrganizationUpdateOne {
	_u.mutation.SetLogoURL(v)
	return _u
}

// SetNillableLogoURL sets the "logo_url" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableLogoURL(v *string) *OrganizationUpdateOne {
	if v != nil {
		_u.SetLogoURL(*v)
	}
	return _u
}

// ClearLogoURL clears the value of the "logo_url" field.
func (_u *OrganizationUpdateOne) ClearLogoURL() *OrganizationUpdateOne {
	_u.mutation.ClearLogoURL()
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *OrganizationUpdateOne) SetOwnerID(v uuid.UUID) *OrganizationUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableOwnerID(v *uuid.UUID) *OrganizationUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *OrganizationUpdateOne) SetStatus(v organization.Status) *OrganizationUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableStatus(v *organization.Status) *OrganizationUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OrganizationUpdateOne) SetUpdatedAt(v time.Time) *OrganizationUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *OrganizationUpdateOne) SetDeletedAt(v time.Time) *OrganizationUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *OrganizationUpdateOne) SetNillableDeletedAt(v *time.Time) *OrganizationUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *OrganizationUpdateOne) ClearDeletedAt() *OrganizationUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// AddMemberIDs adds the "members" edge to the OrganizationMember entity by IDs.
func (_u *OrganizationUpdateOne) AddMemberIDs(ids ...uuid.UUID) *OrganizationUpdateOne {
	_u.mutation.AddMemberIDs(ids...)
	return _u
}

// AddMembers adds the "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdateOne) AddMembers(v ...*OrganizationMember) *OrganizationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddMemberIDs(ids...)
}

// Mutation returns the OrganizationMutation object of the builder.
func (_u *OrganizationUpdateOne) Mutation() *OrganizationMutation {
	return _u.mutation
}

// ClearMembers clears all "members" edges to the OrganizationMember entity.
func (_u *OrganizationUpdateOne) ClearMembers() *OrganizationUpdateOne {
	_u.mutation.ClearMembers()
	return _u
}

// RemoveMemberIDs removes the "members" edge to OrganizationMember entities by IDs.
func (_u *OrganizationUpdateOne) RemoveMemberIDs(ids ...uuid.UUID) *OrganizationUpdateOne {
	_u.mutation.RemoveMemberIDs(ids...)
	return _u
}

// RemoveMembers removes "members" edges to OrganizationMember entities.
func (_u *OrganizationUpdateOne) RemoveMembers(v ...*OrganizationMember) *OrganizationUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveMemberIDs(ids...)
}

// Where appends a list predicates to the OrganizationUpdate builder.
func (_u *OrganizationUpdateOne) Where(ps ...predicate.Organization) *OrganizationUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OrganizationUpdateOne) Select(field string, fields ...string) *OrganizationUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Organization entity.
func (_u *OrganizationUpdateOne) Save(ctx context.Context) (*Organization, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OrganizationUpdateOne) SaveX(ctx context.Context) *Organization {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OrganizationUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OrganizationUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OrganizationUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := organization.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OrganizationUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := organization.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Organization.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Slug(); ok {
		if err := organization.SlugValidator(v); err != nil {
			return &ValidationError{Name: "slug", err: fmt.Errorf(`ent: validator failed for field "Organization.slug": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := organization.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Organization.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OrganizationUpdateOne) sqlSave(ctx context.Context) (_node *Organization, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(organization.Table, organization.Columns, sqlgraph.NewFieldSpec(organization.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Organization.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, organization.FieldID)
		for _, f := range fields {
			if !organization.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != organization.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(organization.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Slug(); ok {
		_spec.SetField(organization.FieldSlug, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(organization.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(organization.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.Domain(); ok {
		_spec.SetField(organization.FieldDomain, field.TypeString, value)
	}
	if _u.mutation.DomainCleared() {
		_spec.ClearField(organization.FieldDomain, field.TypeString)
	}
	if value, ok := _u.mutation.LogoURL(); ok {
		_spec.SetField(organization.FieldLogoURL, field.TypeString, value)
	}
	if _u.mutation.LogoURLCleared() {
		_spec.ClearField(organization.FieldLogoURL, field.TypeString)
	}
	if value, ok := _u.mutation.OwnerID(); ok {
		_spec.SetField(organization.FieldOwnerID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(organization.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(organization.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(organization.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(organization.FieldDeletedAt, field.TypeTime)
	}
	if _u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedMembersIDs(); len(nodes) > 0 && !_u.mutation.MembersCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.MembersIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   organization.MembersTable,
			Columns: []string{organization.MembersColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(organizationmember.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Organization{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{organization.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
