// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/passwordcredential"
	"github.com/identity-platform/internal/ent/user"
)

// PasswordCredential is the model entity for the PasswordCredential schema.
type PasswordCredential struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// PasswordHash holds the value of the "password_hash" field.
	PasswordHash string `json:"-"`
	// Algorithm holds the value of the "algorithm" field.
	Algorithm string `json:"algorithm,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// LastChangedAt holds the value of the "last_changed_at" field.
	LastChangedAt time.Time `json:"last_changed_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PasswordCredentialQuery when eager-loading is set.
	Edges        PasswordCredentialEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PasswordCredentialEdges holds the relations/edges for other nodes in the graph.
type PasswordCredentialEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PasswordCredentialEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PasswordCredential) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case passwordcredential.FieldPasswordHash, passwordcredential.FieldAlgorithm:
			values[i] = new(sql.NullString)
		case passwordcredential.FieldCreatedAt, passwordcredential.FieldUpdatedAt, passwordcredential.FieldLastChangedAt:
			values[i] = new(sql.NullTime)
		case passwordcredential.FieldID, passwordcredential.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PasswordCredential fields.
func (_m *PasswordCredential) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case passwordcredential.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case passwordcredential.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case passwordcredential.FieldPasswordHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password_hash", values[i])
			} else if value.Valid {
				_m.PasswordHash = value.String
			}
		case passwordcredential.FieldAlgorithm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field algorithm", values[i])
			} else if value.Valid {
				_m.Algorithm = value.String
			}
		case passwordcredential.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case passwordcredential.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case passwordcredential.FieldLastChangedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_changed_at", values[i])
			} else if value.Valid {
				_m.LastChangedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PasswordCredential.
// This includes values selected through modifiers, order, etc.
func (_m *PasswordCredential) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PasswordCredential entity.
func (_m *PasswordCredential) QueryUser() *UserQuery {
	return NewPasswordCredentialClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this PasswordCredential.
// Note that you need to call PasswordCredential.Unwrap() before calling this method if this PasswordCredential
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PasswordCredential) Update() *PasswordCredentialUpdateOne {
	return NewPasswordCredentialClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PasswordCredential entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PasswordCredential) Unwrap() *PasswordCredential {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PasswordCredential is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PasswordCredential) String() string {
	var builder strings.Builder
	builder.WriteString("PasswordCredential(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("password_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("algorithm=")
	builder.WriteString(_m.Algorithm)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("last_changed_at=")
	builder.WriteString(_m.LastChangedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// PasswordCredentials is a parsable slice of PasswordCredential.
type PasswordCredentials []*PasswordCredential
