// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/signingkey"
)

// SigningKey is the model entity for the SigningKey schema.
type SigningKey struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Kid holds the value of the "kid" field.
	Kid string `json:"kid,omitempty"`
	// Algorithm holds the value of the "algorithm" field.
	Algorithm string `json:"algorithm,omitempty"`
	// PublicKey holds the value of the "public_key" field.
	PublicKey string `json:"public_key,omitempty"`
	// PrivateKeyEncrypted holds the value of the "private_key_encrypted" field.
	PrivateKeyEncrypted string `json:"-"`
	// Status holds the value of the "status" field.
	Status signingkey.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt    time.Time `json:"expires_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SigningKey) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case signingkey.FieldKid, signingkey.FieldAlgorithm, signingkey.FieldPublicKey, signingkey.FieldPrivateKeyEncrypted, signingkey.FieldStatus:
			values[i] = new(sql.NullString)
		case signingkey.FieldCreatedAt, signingkey.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case signingkey.FieldID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SigningKey fields.
func (_m *SigningKey) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case signingkey.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case signingkey.FieldKid:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field kid", values[i])
			} else if value.Valid {
				_m.Kid = value.String
			}
		case signingkey.FieldAlgorithm:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field algorithm", values[i])
			} else if value.Valid {
				_m.Algorithm = value.String
			}
		case signingkey.FieldPublicKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field public_key", values[i])
			} else if value.Valid {
				_m.PublicKey = value.String
			}
		case signingkey.FieldPrivateKeyEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field private_key_encrypted", values[i])
			} else if value.Valid {
				_m.PrivateKeyEncrypted = value.String
			}
		case signingkey.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = signingkey.Status(value.String)
			}
		case signingkey.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case signingkey.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SigningKey.
// This includes values selected through modifiers, order, etc.
func (_m *SigningKey) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SigningKey.
// Note that you need to call SigningKey.Unwrap() before calling this method if this SigningKey
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SigningKey) Update() *SigningKeyUpdateOne {
	return NewSigningKeyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SigningKey entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SigningKey) Unwrap() *SigningKey {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SigningKey is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SigningKey) String() string {
	var builder strings.Builder
	builder.WriteString("SigningKey(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("kid=")
	builder.WriteString(_m.Kid)
	builder.WriteString(", ")
	builder.WriteString("algorithm=")
	builder.WriteString(_m.Algorithm)
	builder.WriteString(", ")
	builder.WriteString("public_key=")
	builder.WriteString(_m.PublicKey)
	builder.WriteString(", ")
	builder.WriteString("private_key_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SigningKeys is a parsable slice of SigningKey.
type SigningKeys []*SigningKey
