// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/user"
	"github.com/identity-platform/internal/ent/userphone"
)

// UserPhoneCreate is the builder for creating a UserPhone entity.
type UserPhoneCreate struct {
	config
	mutation *UserPhoneMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *UserPhoneCreate) SetUserID(v uuid.UUID) *UserPhoneCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPhone sets the "phone" field.
func (_c *UserPhoneCreate) SetPhone(v string) *UserPhoneCreate {
	_c.mutation.SetPhone(v)
	return _c
}

// SetVerified sets the "verified" field.
func (_c *UserPhoneCreate) SetVerified(v bool) *UserPhoneCreate {
	_c.mutation.SetVerified(v)
	return _c
}

// SetNillableVerified sets the "verified" field if the given value is not nil.
func (_c *UserPhoneCreate) SetNillableVerified(v *bool) *UserPhoneCreate {
	if v != nil {
		_c.SetVerified(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *UserPhoneCreate) SetVerifiedAt(v time.Time) *UserPhoneCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *UserPhoneCreate) SetNillableVerifiedAt(v *time.Time) *UserPhoneCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserPhoneCreate) SetCreatedAt(v time.Time) *UserPhoneCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserPhoneCreate) SetNillableCreatedAt(v *time.Time) *UserPhoneCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserPhoneCreate) SetUpdatedAt(v time.Time) *UserPhoneCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserPhoneCreate) SetNillableUpdatedAt(v *time.Time) *UserPhoneCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *UserPhoneCreate) SetID(v uuid.UUID) *UserPhoneCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *UserPhoneCreate) SetNillableID(v *uuid.UUID) *UserPhoneCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *UserPhoneCreate) SetUser(v *User) *UserPhoneCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the UserPhoneMutation object of the builder.
func (_c *UserPhoneCreate) Mutation() *UserPhoneMutation {
	return _c.mutation
}

// Save creates the UserPhone in the database.
func (_c *UserPhoneCreate) Save(ctx context.Context) (*UserPhone, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserPhoneCreate) SaveX(ctx context.Context) *UserPhone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPhoneCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPhoneCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserPhoneCreate) defaults() {
	if _, ok := _c.mutation.Verified(); !ok {
		v := userphone.DefaultVerified
		_c.mutation.SetVerified(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userphone.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userphone.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := userphone.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserPhoneCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserPhone.user_id"`)}
	}
	if _, ok := _c.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "UserPhone.phone"`)}
	}
	if v, ok := _c.mutation.Phone(); ok {
		if err := userphone.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "UserPhone.phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Verified(); !ok {
		return &ValidationError{Name: "verified", err: errors.New(`ent: missing required field "UserPhone.verified"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserPhone.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserPhone.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "UserPhone.user"`)}
	}
	return nil
}

func (_c *UserPhoneCreate) sqlSave(ctx context.Context) (*UserPhone, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserPhoneCreate) createSpec() (*UserPhone, *sqlgraph.CreateSpec) {
	var (
		_node = &UserPhone{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userphone.Table, sqlgraph.NewFieldSpec(userphone.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Phone(); ok {
		_spec.SetField(userphone.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := _c.mutation.Verified(); ok {
		_spec.SetField(userphone.FieldVerified, field.TypeBool, value)
		_node.Verified = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(userphone.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userphone.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userphone.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   userphone.UserTable,
			Columns: []string{userphone.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// UserPhoneCreateBulk is the builder for creating many UserPhone entities in bulk.
type UserPhoneCreateBulk struct {
	config
	err      error
	builders []*UserPhoneCreate
}

// Save creates the UserPhone entities in the database.
func (_c *UserPhoneCreateBulk) Save(ctx context.Context) ([]*UserPhone, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserPhone, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserPhoneMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserPhoneCreateBulk) SaveX(ctx context.Context) []*UserPhone {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserPhoneCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserPhoneCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
