// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/predicate"
	"github.com/identity-platform/internal/ent/webhook"
	"github.com/identity-platform/internal/ent/webhookevent"
)

// WebhookEventQuery is the builder for querying WebhookEvent entities.
type WebhookEventQuery struct {
	config
	ctx         *QueryContext
	order       []webhookevent.OrderOption
	inters      []Interceptor
	predicates  []predicate.WebhookEvent
	withWebhook *WebhookQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the WebhookEventQuery builder.
func (_q *WebhookEventQuery) Where(ps ...predicate.WebhookEvent) *WebhookEventQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *WebhookEventQuery) Limit(limit int) *WebhookEventQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *WebhookEventQuery) Offset(offset int) *WebhookEventQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *WebhookEventQuery) Unique(unique bool) *WebhookEventQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *WebhookEventQuery) Order(o ...webhookevent.OrderOption) *WebhookEventQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryWebhook chains the current query on the "webhook" edge.
func (_q *WebhookEventQuery) QueryWebhook() *WebhookQuery {
	query := (&WebhookClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(webhookevent.Table, webhookevent.FieldID, selector),
			sqlgraph.To(webhook.Table, webhook.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, webhookevent.WebhookTable, webhookevent.WebhookColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first WebhookEvent entity from the query.
// Returns a *NotFoundError when no WebhookEvent was found.
func (_q *WebhookEventQuery) First(ctx context.Context) (*WebhookEvent, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{webhookevent.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *WebhookEventQuery) FirstX(ctx context.Context) *WebhookEvent {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first WebhookEvent ID from the query.
// Returns a *NotFoundError when no WebhookEvent ID was found.
func (_q *WebhookEventQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{webhookevent.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *WebhookEventQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single WebhookEvent entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one WebhookEvent entity is found.
// Returns a *NotFoundError when no WebhookEvent entities are found.
func (_q *WebhookEventQuery) Only(ctx context.Context) (*WebhookEvent, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{webhookevent.Label}
	default:
		return nil, &NotSingularError{webhookevent.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *WebhookEventQuery) OnlyX(ctx context.Context) *WebhookEvent {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only WebhookEvent ID in the query.
// Returns a *NotSingularError when more than one WebhookEvent ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *WebhookEventQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{webhookevent.Label}
	default:
		err = &NotSingularError{webhookevent.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *WebhookEventQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of WebhookEvents.
func (_q *WebhookEventQuery) All(ctx context.Context) ([]*WebhookEvent, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*WebhookEvent, *WebhookEventQuery]()
	return withInterceptors[[]*WebhookEvent](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *WebhookEventQuery) AllX(ctx context.Context) []*WebhookEvent {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of WebhookEvent IDs.
func (_q *WebhookEventQuery) IDs(ctx context.Context) (ids []uuid.UUID, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(webhookevent.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *WebhookEventQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *WebhookEventQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*WebhookEventQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *WebhookEventQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *WebhookEventQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *WebhookEventQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the WebhookEventQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *WebhookEventQuery) Clone() *WebhookEventQuery {
	if _q == nil {
		return nil
	}
	return &WebhookEventQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]webhookevent.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.WebhookEvent{}, _q.predicates...),
		withWebhook: _q.withWebhook.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithWebhook tells the query-builder to eager-load the nodes that are connected to
// the "webhook" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *WebhookEventQuery) WithWebhook(opts ...func(*WebhookQuery)) *WebhookEventQuery {
	query := (&WebhookClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withWebhook = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		WebhookID uuid.UUID `json:"webhook_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.WebhookEvent.Query().
//		GroupBy(webhookevent.FieldWebhookID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *WebhookEventQuery) GroupBy(field string, fields ...string) *WebhookEventGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &WebhookEventGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = webhookevent.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		WebhookID uuid.UUID `json:"webhook_id,omitempty"`
//	}
//
//	client.WebhookEvent.Query().
//		Select(webhookevent.FieldWebhookID).
//		Scan(ctx, &v)
func (_q *WebhookEventQuery) Select(fields ...string) *WebhookEventSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &WebhookEventSelect{WebhookEventQuery: _q}
	sbuild.label = webhookevent.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a WebhookEventSelect configured with the given aggregations.
func (_q *WebhookEventQuery) Aggregate(fns ...AggregateFunc) *WebhookEventSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *WebhookEventQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !webhookevent.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *WebhookEventQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*WebhookEvent, error) {
	var (
		nodes       = []*WebhookEvent{}
		_spec       = _q.querySpec()
		loadedTypes = [1]bool{
			_q.withWebhook != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*WebhookEvent).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &WebhookEvent{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withWebhook; query != nil {
		if err := _q.loadWebhook(ctx, query, nodes, nil,
			func(n *WebhookEvent, e *Webhook) { n.Edges.Webhook = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *WebhookEventQuery) loadWebhook(ctx context.Context, query *WebhookQuery, nodes []*WebhookEvent, init func(*WebhookEvent), assign func(*WebhookEvent, *Webhook)) error {
	ids := make([]uuid.UUID, 0, len(nodes))
	nodeids := make(map[uuid.UUID][]*WebhookEvent)
	for i := range nodes {
		fk := nodes[i].WebhookID
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(webhook.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "webhook_id" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *WebhookEventQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *WebhookEventQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(webhookevent.Table, webhookevent.Columns, sqlgraph.NewFieldSpec(webhookevent.FieldID, field.TypeUUID))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, webhookevent.FieldID)
		for i := range fields {
			if fields[i] != webhookevent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withWebhook != nil {
			_spec.Node.AddColumnOnce(webhookevent.FieldWebhookID)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *WebhookEventQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(webhookevent.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = webhookevent.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// WebhookEventGroupBy is the group-by builder for WebhookEvent entities.
type WebhookEventGroupBy struct {
	selector
	build *WebhookEventQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *WebhookEventGroupBy) Aggregate(fns ...AggregateFunc) *WebhookEventGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *WebhookEventGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookEventQuery, *WebhookEventGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *WebhookEventGroupBy) sqlScan(ctx context.Context, root *WebhookEventQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// WebhookEventSelect is the builder for selecting fields of WebhookEvent entities.
type WebhookEventSelect struct {
	*WebhookEventQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *WebhookEventSelect) Aggregate(fns ...AggregateFunc) *WebhookEventSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *WebhookEventSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*WebhookEventQuery, *WebhookEventSelect](ctx, _s.WebhookEventQuery, _s, _s.inters, v)
}

func (_s *WebhookEventSelect) sqlScan(ctx context.Context, root *WebhookEventQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
