// Code generated by ent, DO NOT EDIT.

package authorizationcode

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldID, id))
}

// CodeHash applies equality check predicate on the "code_hash" field. It's identical to CodeHashEQ.
func CodeHash(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCodeHash, v))
}

// ClientID applies equality check predicate on the "client_id" field. It's identical to ClientIDEQ.
func ClientID(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldClientID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldUserID, v))
}

// RedirectURI applies equality check predicate on the "redirect_uri" field. It's identical to RedirectURIEQ.
func RedirectURI(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldRedirectURI, v))
}

// CodeChallenge applies equality check predicate on the "code_challenge" field. It's identical to CodeChallengeEQ.
func CodeChallenge(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeMethod applies equality check predicate on the "code_challenge_method" field. It's identical to CodeChallengeMethodEQ.
func CodeChallengeMethod(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// ExpiresAt applies equality check predicate on the "expires_at" field. It's identical to ExpiresAtEQ.
func ExpiresAt(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldExpiresAt, v))
}

// UsedAt applies equality check predicate on the "used_at" field. It's identical to UsedAtEQ.
func UsedAt(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldUsedAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CodeHashEQ applies the EQ predicate on the "code_hash" field.
func CodeHashEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCodeHash, v))
}

// CodeHashNEQ applies the NEQ predicate on the "code_hash" field.
func CodeHashNEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldCodeHash, v))
}

// CodeHashIn applies the In predicate on the "code_hash" field.
func CodeHashIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldCodeHash, vs...))
}

// CodeHashNotIn applies the NotIn predicate on the "code_hash" field.
func CodeHashNotIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldCodeHash, vs...))
}

// CodeHashGT applies the GT predicate on the "code_hash" field.
func CodeHashGT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldCodeHash, v))
}

// CodeHashGTE applies the GTE predicate on the "code_hash" field.
func CodeHashGTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldCodeHash, v))
}

// CodeHashLT applies the LT predicate on the "code_hash" field.
func CodeHashLT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldCodeHash, v))
}

// CodeHashLTE applies the LTE predicate on the "code_hash" field.
func CodeHashLTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldCodeHash, v))
}

// CodeHashContains applies the Contains predicate on the "code_hash" field.
func CodeHashContains(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContains(FieldCodeHash, v))
}

// CodeHashHasPrefix applies the HasPrefix predicate on the "code_hash" field.
func CodeHashHasPrefix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasPrefix(FieldCodeHash, v))
}

// CodeHashHasSuffix applies the HasSuffix predicate on the "code_hash" field.
func CodeHashHasSuffix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasSuffix(FieldCodeHash, v))
}

// CodeHashEqualFold applies the EqualFold predicate on the "code_hash" field.
func CodeHashEqualFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEqualFold(FieldCodeHash, v))
}

// CodeHashContainsFold applies the ContainsFold predicate on the "code_hash" field.
func CodeHashContainsFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContainsFold(FieldCodeHash, v))
}

// ClientIDEQ applies the EQ predicate on the "client_id" field.
func ClientIDEQ(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldClientID, v))
}

// ClientIDNEQ applies the NEQ predicate on the "client_id" field.
func ClientIDNEQ(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldClientID, v))
}

// ClientIDIn applies the In predicate on the "client_id" field.
func ClientIDIn(vs ...uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldClientID, vs...))
}

// ClientIDNotIn applies the NotIn predicate on the "client_id" field.
func ClientIDNotIn(vs ...uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldClientID, vs...))
}

// ClientIDGT applies the GT predicate on the "client_id" field.
func ClientIDGT(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldClientID, v))
}

// ClientIDGTE applies the GTE predicate on the "client_id" field.
func ClientIDGTE(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldClientID, v))
}

// ClientIDLT applies the LT predicate on the "client_id" field.
func ClientIDLT(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldClientID, v))
}

// ClientIDLTE applies the LTE predicate on the "client_id" field.
func ClientIDLTE(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldClientID, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v uuid.UUID) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldUserID, v))
}

// RedirectURIEQ applies the EQ predicate on the "redirect_uri" field.
func RedirectURIEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldRedirectURI, v))
}

// RedirectURINEQ applies the NEQ predicate on the "redirect_uri" field.
func RedirectURINEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldRedirectURI, v))
}

// RedirectURIIn applies the In predicate on the "redirect_uri" field.
func RedirectURIIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldRedirectURI, vs...))
}

// RedirectURINotIn applies the NotIn predicate on the "redirect_uri" field.
func RedirectURINotIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldRedirectURI, vs...))
}

// RedirectURIGT applies the GT predicate on the "redirect_uri" field.
func RedirectURIGT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldRedirectURI, v))
}

// RedirectURIGTE applies the GTE predicate on the "redirect_uri" field.
func RedirectURIGTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldRedirectURI, v))
}

// RedirectURILT applies the LT predicate on the "redirect_uri" field.
func RedirectURILT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldRedirectURI, v))
}

// RedirectURILTE applies the LTE predicate on the "redirect_uri" field.
func RedirectURILTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldRedirectURI, v))
}

// RedirectURIContains applies the Contains predicate on the "redirect_uri" field.
func RedirectURIContains(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContains(FieldRedirectURI, v))
}

// RedirectURIHasPrefix applies the HasPrefix predicate on the "redirect_uri" field.
func RedirectURIHasPrefix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasPrefix(FieldRedirectURI, v))
}

// RedirectURIHasSuffix applies the HasSuffix predicate on the "redirect_uri" field.
func RedirectURIHasSuffix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasSuffix(FieldRedirectURI, v))
}

// RedirectURIEqualFold applies the EqualFold predicate on the "redirect_uri" field.
func RedirectURIEqualFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEqualFold(FieldRedirectURI, v))
}

// RedirectURIContainsFold applies the ContainsFold predicate on the "redirect_uri" field.
func RedirectURIContainsFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContainsFold(FieldRedirectURI, v))
}

// CodeChallengeEQ applies the EQ predicate on the "code_challenge" field.
func CodeChallengeEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCodeChallenge, v))
}

// CodeChallengeNEQ applies the NEQ predicate on the "code_challenge" field.
func CodeChallengeNEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldCodeChallenge, v))
}

// CodeChallengeIn applies the In predicate on the "code_challenge" field.
func CodeChallengeIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldCodeChallenge, vs...))
}

// CodeChallengeNotIn applies the NotIn predicate on the "code_challenge" field.
func CodeChallengeNotIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldCodeChallenge, vs...))
}

// CodeChallengeGT applies the GT predicate on the "code_challenge" field.
func CodeChallengeGT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldCodeChallenge, v))
}

// CodeChallengeGTE applies the GTE predicate on the "code_challenge" field.
func CodeChallengeGTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldCodeChallenge, v))
}

// CodeChallengeLT applies the LT predicate on the "code_challenge" field.
func CodeChallengeLT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldCodeChallenge, v))
}

// CodeChallengeLTE applies the LTE predicate on the "code_challenge" field.
func CodeChallengeLTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldCodeChallenge, v))
}

// CodeChallengeContains applies the Contains predicate on the "code_challenge" field.
func CodeChallengeContains(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContains(FieldCodeChallenge, v))
}

// CodeChallengeHasPrefix applies the HasPrefix predicate on the "code_challenge" field.
func CodeChallengeHasPrefix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasPrefix(FieldCodeChallenge, v))
}

// CodeChallengeHasSuffix applies the HasSuffix predicate on the "code_challenge" field.
func CodeChallengeHasSuffix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasSuffix(FieldCodeChallenge, v))
}

// CodeChallengeIsNil applies the IsNil predicate on the "code_challenge" field.
func CodeChallengeIsNil() predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIsNull(FieldCodeChallenge))
}

// CodeChallengeNotNil applies the NotNil predicate on the "code_challenge" field.
func CodeChallengeNotNil() predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotNull(FieldCodeChallenge))
}

// CodeChallengeEqualFold applies the EqualFold predicate on the "code_challenge" field.
func CodeChallengeEqualFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEqualFold(FieldCodeChallenge, v))
}

// CodeChallengeContainsFold applies the ContainsFold predicate on the "code_challenge" field.
func CodeChallengeContainsFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContainsFold(FieldCodeChallenge, v))
}

// CodeChallengeMethodEQ applies the EQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodNEQ applies the NEQ predicate on the "code_challenge_method" field.
func CodeChallengeMethodNEQ(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodIn applies the In predicate on the "code_challenge_method" field.
func CodeChallengeMethodIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodNotIn applies the NotIn predicate on the "code_challenge_method" field.
func CodeChallengeMethodNotIn(vs ...string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldCodeChallengeMethod, vs...))
}

// CodeChallengeMethodGT applies the GT predicate on the "code_challenge_method" field.
func CodeChallengeMethodGT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodGTE applies the GTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodGTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLT applies the LT predicate on the "code_challenge_method" field.
func CodeChallengeMethodLT(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodLTE applies the LTE predicate on the "code_challenge_method" field.
func CodeChallengeMethodLTE(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContains applies the Contains predicate on the "code_challenge_method" field.
func CodeChallengeMethodContains(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContains(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasPrefix applies the HasPrefix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasPrefix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasPrefix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodHasSuffix applies the HasSuffix predicate on the "code_challenge_method" field.
func CodeChallengeMethodHasSuffix(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldHasSuffix(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodIsNil applies the IsNil predicate on the "code_challenge_method" field.
func CodeChallengeMethodIsNil() predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIsNull(FieldCodeChallengeMethod))
}

// CodeChallengeMethodNotNil applies the NotNil predicate on the "code_challenge_method" field.
func CodeChallengeMethodNotNil() predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotNull(FieldCodeChallengeMethod))
}

// CodeChallengeMethodEqualFold applies the EqualFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodEqualFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEqualFold(FieldCodeChallengeMethod, v))
}

// CodeChallengeMethodContainsFold applies the ContainsFold predicate on the "code_challenge_method" field.
func CodeChallengeMethodContainsFold(v string) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldContainsFold(FieldCodeChallengeMethod, v))
}

// ExpiresAtEQ applies the EQ predicate on the "expires_at" field.
func ExpiresAtEQ(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldExpiresAt, v))
}

// ExpiresAtNEQ applies the NEQ predicate on the "expires_at" field.
func ExpiresAtNEQ(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldExpiresAt, v))
}

// ExpiresAtIn applies the In predicate on the "expires_at" field.
func ExpiresAtIn(vs ...time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldExpiresAt, vs...))
}

// ExpiresAtNotIn applies the NotIn predicate on the "expires_at" field.
func ExpiresAtNotIn(vs ...time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldExpiresAt, vs...))
}

// ExpiresAtGT applies the GT predicate on the "expires_at" field.
func ExpiresAtGT(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldExpiresAt, v))
}

// ExpiresAtGTE applies the GTE predicate on the "expires_at" field.
func ExpiresAtGTE(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldExpiresAt, v))
}

// ExpiresAtLT applies the LT predicate on the "expires_at" field.
func ExpiresAtLT(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldExpiresAt, v))
}

// ExpiresAtLTE applies the LTE predicate on the "expires_at" field.
func ExpiresAtLTE(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldExpiresAt, v))
}

// UsedAtEQ applies the EQ predicate on the "used_at" field.
func UsedAtEQ(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldUsedAt, v))
}

// UsedAtNEQ applies the NEQ predicate on the "used_at" field.
func UsedAtNEQ(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldUsedAt, v))
}

// UsedAtIn applies the In predicate on the "used_at" field.
func UsedAtIn(vs ...time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldUsedAt, vs...))
}

// UsedAtNotIn applies the NotIn predicate on the "used_at" field.
func UsedAtNotIn(vs ...time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldUsedAt, vs...))
}

// UsedAtGT applies the GT predicate on the "used_at" field.
func UsedAtGT(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldUsedAt, v))
}

// UsedAtGTE applies the GTE predicate on the "used_at" field.
func UsedAtGTE(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldUsedAt, v))
}

// UsedAtLT applies the LT predicate on the "used_at" field.
func UsedAtLT(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldUsedAt, v))
}

// UsedAtLTE applies the LTE predicate on the "used_at" field.
func UsedAtLTE(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldUsedAt, v))
}

// UsedAtIsNil applies the IsNil predicate on the "used_at" field.
func UsedAtIsNil() predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIsNull(FieldUsedAt))
}

// UsedAtNotNil applies the NotNil predicate on the "used_at" field.
func UsedAtNotNil() predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotNull(FieldUsedAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AuthorizationCode) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AuthorizationCode) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AuthorizationCode) predicate.AuthorizationCode {
	return predicate.AuthorizationCode(sql.NotPredicates(p))
}
