// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/authorizationcode"
	"github.com/identity-platform/internal/ent/predicate"
)

// AuthorizationCodeUpdate is the builder for updating AuthorizationCode entities.
type AuthorizationCodeUpdate struct {
	config
	hooks    []Hook
	mutation *AuthorizationCodeMutation
}

// Where appends a list predicates to the AuthorizationCodeUpdate builder.
func (_u *AuthorizationCodeUpdate) Where(ps ...predicate.AuthorizationCode) *AuthorizationCodeUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetCodeHash sets the "code_hash" field.
func (_u *AuthorizationCodeUpdate) SetCodeHash(v string) *AuthorizationCodeUpdate {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableCodeHash(v *string) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AuthorizationCodeUpdate) SetClientID(v uuid.UUID) *AuthorizationCodeUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableClientID(v *uuid.UUID) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthorizationCodeUpdate) SetUserID(v uuid.UUID) *AuthorizationCodeUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableUserID(v *uuid.UUID) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *AuthorizationCodeUpdate) SetRedirectURI(v string) *AuthorizationCodeUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableRedirectURI(v *string) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AuthorizationCodeUpdate) SetScopes(v []string) *AuthorizationCodeUpdate {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AuthorizationCodeUpdate) AppendScopes(v []string) *AuthorizationCodeUpdate {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *AuthorizationCodeUpdate) SetCodeChallenge(v string) *AuthorizationCodeUpdate {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableCodeChallenge(v *string) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (_u *AuthorizationCodeUpdate) ClearCodeChallenge() *AuthorizationCodeUpdate {
	_u.mutation.ClearCodeChallenge()
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *AuthorizationCodeUpdate) SetCodeChallengeMethod(v string) *AuthorizationCodeUpdate {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableCodeChallengeMethod(v *string) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (_u *AuthorizationCodeUpdate) ClearCodeChallengeMethod() *AuthorizationCodeUpdate {
	_u.mutation.ClearCodeChallengeMethod()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthorizationCodeUpdate) SetExpiresAt(v time.Time) *AuthorizationCodeUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableExpiresAt(v *time.Time) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *AuthorizationCodeUpdate) SetUsedAt(v time.Time) *AuthorizationCodeUpdate {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *AuthorizationCodeUpdate) SetNillableUsedAt(v *time.Time) *AuthorizationCodeUpdate {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *AuthorizationCodeUpdate) ClearUsedAt() *AuthorizationCodeUpdate {
	_u.mutation.ClearUsedAt()
	return _u
}

// Mutation returns the AuthorizationCodeMutation object of the builder.
func (_u *AuthorizationCodeUpdate) Mutation() *AuthorizationCodeMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthorizationCodeUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthorizationCodeUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AuthorizationCodeUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthorizationCodeUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthorizationCodeUpdate) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := authorizationcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := authorizationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.redirect_uri": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthorizationCodeUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authorizationcode.Table, authorizationcode.Columns, sqlgraph.NewFieldSpec(authorizationcode.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(authorizationcode.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(authorizationcode.FieldClientID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authorizationcode.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(authorizationcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(authorizationcode.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, authorizationcode.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(authorizationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if _u.mutation.CodeChallengeCleared() {
		_spec.ClearField(authorizationcode.FieldCodeChallenge, field.TypeString)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(authorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if _u.mutation.CodeChallengeMethodCleared() {
		_spec.ClearField(authorizationcode.FieldCodeChallengeMethod, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(authorizationcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(authorizationcode.FieldUsedAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AuthorizationCodeUpdateOne is the builder for updating a single AuthorizationCode entity.
type AuthorizationCodeUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthorizationCodeMutation
}

// SetCodeHash sets the "code_hash" field.
func (_u *AuthorizationCodeUpdateOne) SetCodeHash(v string) *AuthorizationCodeUpdateOne {
	_u.mutation.SetCodeHash(v)
	return _u
}

// SetNillableCodeHash sets the "code_hash" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableCodeHash(v *string) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeHash(*v)
	}
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *AuthorizationCodeUpdateOne) SetClientID(v uuid.UUID) *AuthorizationCodeUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableClientID(v *uuid.UUID) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *AuthorizationCodeUpdateOne) SetUserID(v uuid.UUID) *AuthorizationCodeUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableUserID(v *uuid.UUID) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *AuthorizationCodeUpdateOne) SetRedirectURI(v string) *AuthorizationCodeUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableRedirectURI(v *string) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetScopes sets the "scopes" field.
func (_u *AuthorizationCodeUpdateOne) SetScopes(v []string) *AuthorizationCodeUpdateOne {
	_u.mutation.SetScopes(v)
	return _u
}

// AppendScopes appends value to the "scopes" field.
func (_u *AuthorizationCodeUpdateOne) AppendScopes(v []string) *AuthorizationCodeUpdateOne {
	_u.mutation.AppendScopes(v)
	return _u
}

// SetCodeChallenge sets the "code_challenge" field.
func (_u *AuthorizationCodeUpdateOne) SetCodeChallenge(v string) *AuthorizationCodeUpdateOne {
	_u.mutation.SetCodeChallenge(v)
	return _u
}

// SetNillableCodeChallenge sets the "code_challenge" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableCodeChallenge(v *string) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallenge(*v)
	}
	return _u
}

// ClearCodeChallenge clears the value of the "code_challenge" field.
func (_u *AuthorizationCodeUpdateOne) ClearCodeChallenge() *AuthorizationCodeUpdateOne {
	_u.mutation.ClearCodeChallenge()
	return _u
}

// SetCodeChallengeMethod sets the "code_challenge_method" field.
func (_u *AuthorizationCodeUpdateOne) SetCodeChallengeMethod(v string) *AuthorizationCodeUpdateOne {
	_u.mutation.SetCodeChallengeMethod(v)
	return _u
}

// SetNillableCodeChallengeMethod sets the "code_challenge_method" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableCodeChallengeMethod(v *string) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetCodeChallengeMethod(*v)
	}
	return _u
}

// ClearCodeChallengeMethod clears the value of the "code_challenge_method" field.
func (_u *AuthorizationCodeUpdateOne) ClearCodeChallengeMethod() *AuthorizationCodeUpdateOne {
	_u.mutation.ClearCodeChallengeMethod()
	return _u
}

// SetExpiresAt sets the "expires_at" field.
func (_u *AuthorizationCodeUpdateOne) SetExpiresAt(v time.Time) *AuthorizationCodeUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
}

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableExpiresAt(v *time.Time) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
	}
	return _u
}

// SetUsedAt sets the "used_at" field.
func (_u *AuthorizationCodeUpdateOne) SetUsedAt(v time.Time) *AuthorizationCodeUpdateOne {
	_u.mutation.SetUsedAt(v)
	return _u
}

// SetNillableUsedAt sets the "used_at" field if the given value is not nil.
func (_u *AuthorizationCodeUpdateOne) SetNillableUsedAt(v *time.Time) *AuthorizationCodeUpdateOne {
	if v != nil {
		_u.SetUsedAt(*v)
	}
	return _u
}

// ClearUsedAt clears the value of the "used_at" field.
func (_u *AuthorizationCodeUpdateOne) ClearUsedAt() *AuthorizationCodeUpdateOne {
	_u.mutation.ClearUsedAt()
	return _u
}

// Mutation returns the AuthorizationCodeMutation object of the builder.
func (_u *AuthorizationCodeUpdateOne) Mutation() *AuthorizationCodeMutation {
	return _u.mutation
}

// Where appends a list predicates to the AuthorizationCodeUpdate builder.
func (_u *AuthorizationCodeUpdateOne) Where(ps ...predicate.AuthorizationCode) *AuthorizationCodeUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthorizationCodeUpdateOne) Select(field string, fields ...string) *AuthorizationCodeUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AuthorizationCode entity.
func (_u *AuthorizationCodeUpdateOne) Save(ctx context.Context) (*AuthorizationCode, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthorizationCodeUpdateOne) SaveX(ctx context.Context) *AuthorizationCode {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AuthorizationCodeUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthorizationCodeUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AuthorizationCodeUpdateOne) check() error {
	if v, ok := _u.mutation.CodeHash(); ok {
		if err := authorizationcode.CodeHashValidator(v); err != nil {
			return &ValidationError{Name: "code_hash", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.code_hash": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := authorizationcode.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "AuthorizationCode.redirect_uri": %w`, err)}
		}
	}
	return nil
}

func (_u *AuthorizationCodeUpdateOne) sqlSave(ctx context.Context) (_node *AuthorizationCode, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(authorizationcode.Table, authorizationcode.Columns, sqlgraph.NewFieldSpec(authorizationcode.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthorizationCode.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authorizationcode.FieldID)
		for _, f := range fields {
			if !authorizationcode.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != authorizationcode.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CodeHash(); ok {
		_spec.SetField(authorizationcode.FieldCodeHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(authorizationcode.FieldClientID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(authorizationcode.FieldUserID, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(authorizationcode.FieldRedirectURI, field.TypeString, value)
	}
	if value, ok := _u.mutation.Scopes(); ok {
		_spec.SetField(authorizationcode.FieldScopes, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedScopes(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, authorizationcode.FieldScopes, value)
		})
	}
	if value, ok := _u.mutation.CodeChallenge(); ok {
		_spec.SetField(authorizationcode.FieldCodeChallenge, field.TypeString, value)
	}
	if _u.mutation.CodeChallengeCleared() {
		_spec.ClearField(authorizationcode.FieldCodeChallenge, field.TypeString)
	}
	if value, ok := _u.mutation.CodeChallengeMethod(); ok {
		_spec.SetField(authorizationcode.FieldCodeChallengeMethod, field.TypeString, value)
	}
	if _u.mutation.CodeChallengeMethodCleared() {
		_spec.ClearField(authorizationcode.FieldCodeChallengeMethod, field.TypeString)
	}
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(authorizationcode.FieldExpiresAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.UsedAt(); ok {
		_spec.SetField(authorizationcode.FieldUsedAt, field.TypeTime, value)
	}
	if _u.mutation.UsedAtCleared() {
		_spec.ClearField(authorizationcode.FieldUsedAt, field.TypeTime)
	}
	_node = &AuthorizationCode{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authorizationcode.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
