// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/oauthclient"
	"github.com/identity-platform/internal/ent/oauthredirecturi"
	"github.com/identity-platform/internal/ent/predicate"
)

// OAuthRedirectURIUpdate is the builder for updating OAuthRedirectURI entities.
type OAuthRedirectURIUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthRedirectURIMutation
}

// Where appends a list predicates to the OAuthRedirectURIUpdate builder.
func (_u *OAuthRedirectURIUpdate) Where(ps ...predicate.OAuthRedirectURI) *OAuthRedirectURIUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRedirectURIUpdate) SetClientID(v uuid.UUID) *OAuthRedirectURIUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRedirectURIUpdate) SetNillableClientID(v *uuid.UUID) *OAuthRedirectURIUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthRedirectURIUpdate) SetRedirectURI(v string) *OAuthRedirectURIUpdate {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthRedirectURIUpdate) SetNillableRedirectURI(v *string) *OAuthRedirectURIUpdate {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetOauthClientID sets the "oauth_client" edge to the OAuthClient entity by ID.
func (_u *OAuthRedirectURIUpdate) SetOauthClientID(id uuid.UUID) *OAuthRedirectURIUpdate {
	_u.mutation.SetOauthClientID(id)
	return _u
}

// SetOauthClient sets the "oauth_client" edge to the OAuthClient entity.
func (_u *OAuthRedirectURIUpdate) SetOauthClient(v *OAuthClient) *OAuthRedirectURIUpdate {
	return _u.SetOauthClientID(v.ID)
}

// Mutation returns the OAuthRedirectURIMutation object of the builder.
func (_u *OAuthRedirectURIUpdate) Mutation() *OAuthRedirectURIMutation {
	return _u.mutation
}

// ClearOauthClient clears the "oauth_client" edge to the OAuthClient entity.
func (_u *OAuthRedirectURIUpdate) ClearOauthClient() *OAuthRedirectURIUpdate {
	_u.mutation.ClearOauthClient()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthRedirectURIUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRedirectURIUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthRedirectURIUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRedirectURIUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRedirectURIUpdate) check() error {
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthredirecturi.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthRedirectURI.redirect_uri": %w`, err)}
		}
	}
	if _u.mutation.OauthClientCleared() && len(_u.mutation.OauthClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthRedirectURI.oauth_client"`)
	}
	return nil
}

func (_u *OAuthRedirectURIUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthredirecturi.Table, oauthredirecturi.Columns, sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthredirecturi.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.OauthClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthredirecturi.OauthClientTable,
			Columns: []string{oauthredirecturi.OauthClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OauthClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthredirecturi.OauthClientTable,
			Columns: []string{oauthredirecturi.OauthClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthredirecturi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthRedirectURIUpdateOne is the builder for updating a single OAuthRedirectURI entity.
type OAuthRedirectURIUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthRedirectURIMutation
}

// SetClientID sets the "client_id" field.
func (_u *OAuthRedirectURIUpdateOne) SetClientID(v uuid.UUID) *OAuthRedirectURIUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthRedirectURIUpdateOne) SetNillableClientID(v *uuid.UUID) *OAuthRedirectURIUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetRedirectURI sets the "redirect_uri" field.
func (_u *OAuthRedirectURIUpdateOne) SetRedirectURI(v string) *OAuthRedirectURIUpdateOne {
	_u.mutation.SetRedirectURI(v)
	return _u
}

// SetNillableRedirectURI sets the "redirect_uri" field if the given value is not nil.
func (_u *OAuthRedirectURIUpdateOne) SetNillableRedirectURI(v *string) *OAuthRedirectURIUpdateOne {
	if v != nil {
		_u.SetRedirectURI(*v)
	}
	return _u
}

// SetOauthClientID sets the "oauth_client" edge to the OAuthClient entity by ID.
func (_u *OAuthRedirectURIUpdateOne) SetOauthClientID(id uuid.UUID) *OAuthRedirectURIUpdateOne {
	_u.mutation.SetOauthClientID(id)
	return _u
}

// SetOauthClient sets the "oauth_client" edge to the OAuthClient entity.
func (_u *OAuthRedirectURIUpdateOne) SetOauthClient(v *OAuthClient) *OAuthRedirectURIUpdateOne {
	return _u.SetOauthClientID(v.ID)
}

// Mutation returns the OAuthRedirectURIMutation object of the builder.
func (_u *OAuthRedirectURIUpdateOne) Mutation() *OAuthRedirectURIMutation {
	return _u.mutation
}

// ClearOauthClient clears the "oauth_client" edge to the OAuthClient entity.
func (_u *OAuthRedirectURIUpdateOne) ClearOauthClient() *OAuthRedirectURIUpdateOne {
	_u.mutation.ClearOauthClient()
	return _u
}

// Where appends a list predicates to the OAuthRedirectURIUpdate builder.
func (_u *OAuthRedirectURIUpdateOne) Where(ps ...predicate.OAuthRedirectURI) *OAuthRedirectURIUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthRedirectURIUpdateOne) Select(field string, fields ...string) *OAuthRedirectURIUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthRedirectURI entity.
func (_u *OAuthRedirectURIUpdateOne) Save(ctx context.Context) (*OAuthRedirectURI, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthRedirectURIUpdateOne) SaveX(ctx context.Context) *OAuthRedirectURI {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthRedirectURIUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthRedirectURIUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthRedirectURIUpdateOne) check() error {
	if v, ok := _u.mutation.RedirectURI(); ok {
		if err := oauthredirecturi.RedirectURIValidator(v); err != nil {
			return &ValidationError{Name: "redirect_uri", err: fmt.Errorf(`ent: validator failed for field "OAuthRedirectURI.redirect_uri": %w`, err)}
		}
	}
	if _u.mutation.OauthClientCleared() && len(_u.mutation.OauthClientIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "OAuthRedirectURI.oauth_client"`)
	}
	return nil
}

func (_u *OAuthRedirectURIUpdateOne) sqlSave(ctx context.Context) (_node *OAuthRedirectURI, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthredirecturi.Table, oauthredirecturi.Columns, sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthRedirectURI.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthredirecturi.FieldID)
		for _, f := range fields {
			if !oauthredirecturi.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthredirecturi.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.RedirectURI(); ok {
		_spec.SetField(oauthredirecturi.FieldRedirectURI, field.TypeString, value)
	}
	if _u.mutation.OauthClientCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthredirecturi.OauthClientTable,
			Columns: []string{oauthredirecturi.OauthClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OauthClientIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   oauthredirecturi.OauthClientTable,
			Columns: []string{oauthredirecturi.OauthClientColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthRedirectURI{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthredirecturi.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
