// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/oauthclient"
	"github.com/identity-platform/internal/ent/oauthconsent"
	"github.com/identity-platform/internal/ent/user"
)

// OAuthConsent is the model entity for the OAuthConsent schema.
type OAuthConsent struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID uuid.UUID `json:"user_id,omitempty"`
	// ClientID holds the value of the "client_id" field.
	ClientID uuid.UUID `json:"client_id,omitempty"`
	// Scopes holds the value of the "scopes" field.
	Scopes []string `json:"scopes,omitempty"`
	// Status holds the value of the "status" field.
	Status oauthconsent.Status `json:"status,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the OAuthConsentQuery when eager-loading is set.
	Edges        OAuthConsentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// OAuthConsentEdges holds the relations/edges for other nodes in the graph.
type OAuthConsentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// OauthClient holds the value of the oauth_client edge.
	OauthClient *OAuthClient `json:"oauth_client,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthConsentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// OauthClientOrErr returns the OauthClient value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e OAuthConsentEdges) OauthClientOrErr() (*OAuthClient, error) {
	if e.OauthClient != nil {
		return e.OauthClient, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: oauthclient.Label}
	}
	return nil, &NotLoadedError{edge: "oauth_client"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*OAuthConsent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case oauthconsent.FieldScopes:
			values[i] = new([]byte)
		case oauthconsent.FieldStatus:
			values[i] = new(sql.NullString)
		case oauthconsent.FieldCreatedAt, oauthconsent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case oauthconsent.FieldID, oauthconsent.FieldUserID, oauthconsent.FieldClientID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the OAuthConsent fields.
func (_m *OAuthConsent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case oauthconsent.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case oauthconsent.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case oauthconsent.FieldClientID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field client_id", values[i])
			} else if value != nil {
				_m.ClientID = *value
			}
		case oauthconsent.FieldScopes:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scopes", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Scopes); err != nil {
					return fmt.Errorf("unmarshal field scopes: %w", err)
				}
			}
		case oauthconsent.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = oauthconsent.Status(value.String)
			}
		case oauthconsent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case oauthconsent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the OAuthConsent.
// This includes values selected through modifiers, order, etc.
func (_m *OAuthConsent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the OAuthConsent entity.
func (_m *OAuthConsent) QueryUser() *UserQuery {
	return NewOAuthConsentClient(_m.config).QueryUser(_m)
}

// QueryOauthClient queries the "oauth_client" edge of the OAuthConsent entity.
func (_m *OAuthConsent) QueryOauthClient() *OAuthClientQuery {
	return NewOAuthConsentClient(_m.config).QueryOauthClient(_m)
}

// Update returns a builder for updating this OAuthConsent.
// Note that you need to call OAuthConsent.Unwrap() before calling this method if this OAuthConsent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *OAuthConsent) Update() *OAuthConsentUpdateOne {
	return NewOAuthConsentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the OAuthConsent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *OAuthConsent) Unwrap() *OAuthConsent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: OAuthConsent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *OAuthConsent) String() string {
	var builder strings.Builder
	builder.WriteString("OAuthConsent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("client_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ClientID))
	builder.WriteString(", ")
	builder.WriteString("scopes=")
	builder.WriteString(fmt.Sprintf("%v", _m.Scopes))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// OAuthConsents is a parsable slice of OAuthConsent.
type OAuthConsents []*OAuthConsent
