// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/oauthclient"
	"github.com/identity-platform/internal/ent/oauthconsent"
	"github.com/identity-platform/internal/ent/oauthredirecturi"
	"github.com/identity-platform/internal/ent/predicate"
)

// OAuthClientUpdate is the builder for updating OAuthClient entities.
type OAuthClientUpdate struct {
	config
	hooks    []Hook
	mutation *OAuthClientMutation
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdate) Where(ps ...predicate.OAuthClient) *OAuthClientUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetClientID sets the "client_id" field.
func (_u *OAuthClientUpdate) SetClientID(v string) *OAuthClientUpdate {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientID(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdate) SetName(v string) *OAuthClientUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableName(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OAuthClientUpdate) SetDescription(v string) *OAuthClientUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableDescription(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *OAuthClientUpdate) ClearDescription() *OAuthClientUpdate {
	_u.mutation.ClearDescription()
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *OAuthClientUpdate) SetClientType(v oauthclient.ClientType) *OAuthClientUpdate {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientType(v *oauthclient.ClientType) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OAuthClientUpdate) SetClientSecretHash(v string) *OAuthClientUpdate {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableClientSecretHash(v *string) *OAuthClientUpdate {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (_u *OAuthClientUpdate) ClearClientSecretHash() *OAuthClientUpdate {
	_u.mutation.ClearClientSecretHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthClientUpdate) SetStatus(v oauthclient.Status) *OAuthClientUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableStatus(v *oauthclient.Status) *OAuthClientUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *OAuthClientUpdate) SetCreatedBy(v uuid.UUID) *OAuthClientUpdate {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *OAuthClientUpdate) SetNillableCreatedBy(v *uuid.UUID) *OAuthClientUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdate) SetUpdatedAt(v time.Time) *OAuthClientUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRedirectURIIDs adds the "redirect_uris" edge to the OAuthRedirectURI entity by IDs.
func (_u *OAuthClientUpdate) AddRedirectURIIDs(ids ...uuid.UUID) *OAuthClientUpdate {
	_u.mutation.AddRedirectURIIDs(ids...)
	return _u
}

// AddRedirectUris adds the "redirect_uris" edges to the OAuthRedirectURI entity.
func (_u *OAuthClientUpdate) AddRedirectUris(v ...*OAuthRedirectURI) *OAuthClientUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedirectURIIDs(ids...)
}

// AddConsentIDs adds the "consents" edge to the OAuthConsent entity by IDs.
func (_u *OAuthClientUpdate) AddConsentIDs(ids ...uuid.UUID) *OAuthClientUpdate {
	_u.mutation.AddConsentIDs(ids...)
	return _u
}

// AddConsents adds the "consents" edges to the OAuthConsent entity.
func (_u *OAuthClientUpdate) AddConsents(v ...*OAuthConsent) *OAuthClientUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConsentIDs(ids...)
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdate) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// ClearRedirectUris clears all "redirect_uris" edges to the OAuthRedirectURI entity.
func (_u *OAuthClientUpdate) ClearRedirectUris() *OAuthClientUpdate {
	_u.mutation.ClearRedirectUris()
	return _u
}

// RemoveRedirectURIIDs removes the "redirect_uris" edge to OAuthRedirectURI entities by IDs.
func (_u *OAuthClientUpdate) RemoveRedirectURIIDs(ids ...uuid.UUID) *OAuthClientUpdate {
	_u.mutation.RemoveRedirectURIIDs(ids...)
	return _u
}

// RemoveRedirectUris removes "redirect_uris" edges to OAuthRedirectURI entities.
func (_u *OAuthClientUpdate) RemoveRedirectUris(v ...*OAuthRedirectURI) *OAuthClientUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedirectURIIDs(ids...)
}

// ClearConsents clears all "consents" edges to the OAuthConsent entity.
func (_u *OAuthClientUpdate) ClearConsents() *OAuthClientUpdate {
	_u.mutation.ClearConsents()
	return _u
}

// RemoveConsentIDs removes the "consents" edge to OAuthConsent entities by IDs.
func (_u *OAuthClientUpdate) RemoveConsentIDs(ids ...uuid.UUID) *OAuthClientUpdate {
	_u.mutation.RemoveConsentIDs(ids...)
	return _u
}

// RemoveConsents removes "consents" edges to OAuthConsent entities.
func (_u *OAuthClientUpdate) RemoveConsents(v ...*OAuthConsent) *OAuthClientUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConsentIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *OAuthClientUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *OAuthClientUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdate) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthclient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(oauthclient.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(oauthclient.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
	}
	if _u.mutation.ClientSecretHashCleared() {
		_spec.ClearField(oauthclient.FieldClientSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthclient.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(oauthclient.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RedirectUrisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedirectUrisIDs(); len(nodes) > 0 && !_u.mutation.RedirectUrisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedirectUrisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConsentsIDs(); len(nodes) > 0 && !_u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// OAuthClientUpdateOne is the builder for updating a single OAuthClient entity.
type OAuthClientUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *OAuthClientMutation
}

// SetClientID sets the "client_id" field.
func (_u *OAuthClientUpdateOne) SetClientID(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientID(v)
	return _u
}

// SetNillableClientID sets the "client_id" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientID(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *OAuthClientUpdateOne) SetName(v string) *OAuthClientUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableName(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *OAuthClientUpdateOne) SetDescription(v string) *OAuthClientUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableDescription(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// ClearDescription clears the value of the "description" field.
func (_u *OAuthClientUpdateOne) ClearDescription() *OAuthClientUpdateOne {
	_u.mutation.ClearDescription()
	return _u
}

// SetClientType sets the "client_type" field.
func (_u *OAuthClientUpdateOne) SetClientType(v oauthclient.ClientType) *OAuthClientUpdateOne {
	_u.mutation.SetClientType(v)
	return _u
}

// SetNillableClientType sets the "client_type" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientType(v *oauthclient.ClientType) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientType(*v)
	}
	return _u
}

// SetClientSecretHash sets the "client_secret_hash" field.
func (_u *OAuthClientUpdateOne) SetClientSecretHash(v string) *OAuthClientUpdateOne {
	_u.mutation.SetClientSecretHash(v)
	return _u
}

// SetNillableClientSecretHash sets the "client_secret_hash" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableClientSecretHash(v *string) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetClientSecretHash(*v)
	}
	return _u
}

// ClearClientSecretHash clears the value of the "client_secret_hash" field.
func (_u *OAuthClientUpdateOne) ClearClientSecretHash() *OAuthClientUpdateOne {
	_u.mutation.ClearClientSecretHash()
	return _u
}

// SetStatus sets the "status" field.
func (_u *OAuthClientUpdateOne) SetStatus(v oauthclient.Status) *OAuthClientUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableStatus(v *oauthclient.Status) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *OAuthClientUpdateOne) SetCreatedBy(v uuid.UUID) *OAuthClientUpdateOne {
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *OAuthClientUpdateOne) SetNillableCreatedBy(v *uuid.UUID) *OAuthClientUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *OAuthClientUpdateOne) SetUpdatedAt(v time.Time) *OAuthClientUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// AddRedirectURIIDs adds the "redirect_uris" edge to the OAuthRedirectURI entity by IDs.
func (_u *OAuthClientUpdateOne) AddRedirectURIIDs(ids ...uuid.UUID) *OAuthClientUpdateOne {
	_u.mutation.AddRedirectURIIDs(ids...)
	return _u
}

// AddRedirectUris adds the "redirect_uris" edges to the OAuthRedirectURI entity.
func (_u *OAuthClientUpdateOne) AddRedirectUris(v ...*OAuthRedirectURI) *OAuthClientUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddRedirectURIIDs(ids...)
}

// AddConsentIDs adds the "consents" edge to the OAuthConsent entity by IDs.
func (_u *OAuthClientUpdateOne) AddConsentIDs(ids ...uuid.UUID) *OAuthClientUpdateOne {
	_u.mutation.AddConsentIDs(ids...)
	return _u
}

// AddConsents adds the "consents" edges to the OAuthConsent entity.
func (_u *OAuthClientUpdateOne) AddConsents(v ...*OAuthConsent) *OAuthClientUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddConsentIDs(ids...)
}

// Mutation returns the OAuthClientMutation object of the builder.
func (_u *OAuthClientUpdateOne) Mutation() *OAuthClientMutation {
	return _u.mutation
}

// ClearRedirectUris clears all "redirect_uris" edges to the OAuthRedirectURI entity.
func (_u *OAuthClientUpdateOne) ClearRedirectUris() *OAuthClientUpdateOne {
	_u.mutation.ClearRedirectUris()
	return _u
}

// RemoveRedirectURIIDs removes the "redirect_uris" edge to OAuthRedirectURI entities by IDs.
func (_u *OAuthClientUpdateOne) RemoveRedirectURIIDs(ids ...uuid.UUID) *OAuthClientUpdateOne {
	_u.mutation.RemoveRedirectURIIDs(ids...)
	return _u
}

// RemoveRedirectUris removes "redirect_uris" edges to OAuthRedirectURI entities.
func (_u *OAuthClientUpdateOne) RemoveRedirectUris(v ...*OAuthRedirectURI) *OAuthClientUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveRedirectURIIDs(ids...)
}

// ClearConsents clears all "consents" edges to the OAuthConsent entity.
func (_u *OAuthClientUpdateOne) ClearConsents() *OAuthClientUpdateOne {
	_u.mutation.ClearConsents()
	return _u
}

// RemoveConsentIDs removes the "consents" edge to OAuthConsent entities by IDs.
func (_u *OAuthClientUpdateOne) RemoveConsentIDs(ids ...uuid.UUID) *OAuthClientUpdateOne {
	_u.mutation.RemoveConsentIDs(ids...)
	return _u
}

// RemoveConsents removes "consents" edges to OAuthConsent entities.
func (_u *OAuthClientUpdateOne) RemoveConsents(v ...*OAuthConsent) *OAuthClientUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveConsentIDs(ids...)
}

// Where appends a list predicates to the OAuthClientUpdate builder.
func (_u *OAuthClientUpdateOne) Where(ps ...predicate.OAuthClient) *OAuthClientUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *OAuthClientUpdateOne) Select(field string, fields ...string) *OAuthClientUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated OAuthClient entity.
func (_u *OAuthClientUpdateOne) Save(ctx context.Context) (*OAuthClient, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) SaveX(ctx context.Context) *OAuthClient {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *OAuthClientUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *OAuthClientUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *OAuthClientUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := oauthclient.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *OAuthClientUpdateOne) check() error {
	if v, ok := _u.mutation.ClientID(); ok {
		if err := oauthclient.ClientIDValidator(v); err != nil {
			return &ValidationError{Name: "client_id", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := oauthclient.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ClientType(); ok {
		if err := oauthclient.ClientTypeValidator(v); err != nil {
			return &ValidationError{Name: "client_type", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.client_type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := oauthclient.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OAuthClient.status": %w`, err)}
		}
	}
	return nil
}

func (_u *OAuthClientUpdateOne) sqlSave(ctx context.Context) (_node *OAuthClient, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(oauthclient.Table, oauthclient.Columns, sqlgraph.NewFieldSpec(oauthclient.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "OAuthClient.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, oauthclient.FieldID)
		for _, f := range fields {
			if !oauthclient.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != oauthclient.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ClientID(); ok {
		_spec.SetField(oauthclient.FieldClientID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(oauthclient.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(oauthclient.FieldDescription, field.TypeString, value)
	}
	if _u.mutation.DescriptionCleared() {
		_spec.ClearField(oauthclient.FieldDescription, field.TypeString)
	}
	if value, ok := _u.mutation.ClientType(); ok {
		_spec.SetField(oauthclient.FieldClientType, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.ClientSecretHash(); ok {
		_spec.SetField(oauthclient.FieldClientSecretHash, field.TypeString, value)
	}
	if _u.mutation.ClientSecretHashCleared() {
		_spec.ClearField(oauthclient.FieldClientSecretHash, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(oauthclient.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(oauthclient.FieldCreatedBy, field.TypeUUID, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(oauthclient.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.RedirectUrisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedRedirectUrisIDs(); len(nodes) > 0 && !_u.mutation.RedirectUrisCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RedirectUrisIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.RedirectUrisTable,
			Columns: []string{oauthclient.RedirectUrisColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthredirecturi.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedConsentsIDs(); len(nodes) > 0 && !_u.mutation.ConsentsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConsentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   oauthclient.ConsentsTable,
			Columns: []string{oauthclient.ConsentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(oauthconsent.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &OAuthClient{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{oauthclient.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
