// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/identity-platform/internal/ent/passwordcredential"
	"github.com/identity-platform/internal/ent/predicate"
	"github.com/identity-platform/internal/ent/user"
)

// PasswordCredentialUpdate is the builder for updating PasswordCredential entities.
type PasswordCredentialUpdate struct {
	config
	hooks    []Hook
	mutation *PasswordCredentialMutation
}

// Where appends a list predicates to the PasswordCredentialUpdate builder.
func (_u *PasswordCredentialUpdate) Where(ps ...predicate.PasswordCredential) *PasswordCredentialUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PasswordCredentialUpdate) SetUserID(v uuid.UUID) *PasswordCredentialUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PasswordCredentialUpdate) SetNillableUserID(v *uuid.UUID) *PasswordCredentialUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *PasswordCredentialUpdate) SetPasswordHash(v string) *PasswordCredentialUpdate {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *PasswordCredentialUpdate) SetNillablePasswordHash(v *string) *PasswordCredentialUpdate {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAlgorithm sets the "algorithm" field.
func (_u *PasswordCredentialUpdate) SetAlgorithm(v string) *PasswordCredentialUpdate {
	_u.mutation.SetAlgorithm(v)
	return _u
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_u *PasswordCredentialUpdate) SetNillableAlgorithm(v *string) *PasswordCredentialUpdate {
	if v != nil {
		_u.SetAlgorithm(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasswordCredentialUpdate) SetUpdatedAt(v time.Time) *PasswordCredentialUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastChangedAt sets the "last_changed_at" field.
func (_u *PasswordCredentialUpdate) SetLastChangedAt(v time.Time) *PasswordCredentialUpdate {
	_u.mutation.SetLastChangedAt(v)
	return _u
}

// SetNillableLastChangedAt sets the "last_changed_at" field if the given value is not nil.
func (_u *PasswordCredentialUpdate) SetNillableLastChangedAt(v *time.Time) *PasswordCredentialUpdate {
	if v != nil {
		_u.SetLastChangedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasswordCredentialUpdate) SetUser(v *User) *PasswordCredentialUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PasswordCredentialMutation object of the builder.
func (_u *PasswordCredentialUpdate) Mutation() *PasswordCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasswordCredentialUpdate) ClearUser() *PasswordCredentialUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PasswordCredentialUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasswordCredentialUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PasswordCredentialUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasswordCredentialUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasswordCredentialUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passwordcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasswordCredentialUpdate) check() error {
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := passwordcredential.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "PasswordCredential.password_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasswordCredential.user"`)
	}
	return nil
}

func (_u *PasswordCredentialUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passwordcredential.Table, passwordcredential.Columns, sqlgraph.NewFieldSpec(passwordcredential.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(passwordcredential.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algorithm(); ok {
		_spec.SetField(passwordcredential.FieldAlgorithm, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passwordcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastChangedAt(); ok {
		_spec.SetField(passwordcredential.FieldLastChangedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   passwordcredential.UserTable,
			Columns: []string{passwordcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   passwordcredential.UserTable,
			Columns: []string{passwordcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passwordcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PasswordCredentialUpdateOne is the builder for updating a single PasswordCredential entity.
type PasswordCredentialUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PasswordCredentialMutation
}

// SetUserID sets the "user_id" field.
func (_u *PasswordCredentialUpdateOne) SetUserID(v uuid.UUID) *PasswordCredentialUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PasswordCredentialUpdateOne) SetNillableUserID(v *uuid.UUID) *PasswordCredentialUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPasswordHash sets the "password_hash" field.
func (_u *PasswordCredentialUpdateOne) SetPasswordHash(v string) *PasswordCredentialUpdateOne {
	_u.mutation.SetPasswordHash(v)
	return _u
}

// SetNillablePasswordHash sets the "password_hash" field if the given value is not nil.
func (_u *PasswordCredentialUpdateOne) SetNillablePasswordHash(v *string) *PasswordCredentialUpdateOne {
	if v != nil {
		_u.SetPasswordHash(*v)
	}
	return _u
}

// SetAlgorithm sets the "algorithm" field.
func (_u *PasswordCredentialUpdateOne) SetAlgorithm(v string) *PasswordCredentialUpdateOne {
	_u.mutation.SetAlgorithm(v)
	return _u
}

// SetNillableAlgorithm sets the "algorithm" field if the given value is not nil.
func (_u *PasswordCredentialUpdateOne) SetNillableAlgorithm(v *string) *PasswordCredentialUpdateOne {
	if v != nil {
		_u.SetAlgorithm(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *PasswordCredentialUpdateOne) SetUpdatedAt(v time.Time) *PasswordCredentialUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetLastChangedAt sets the "last_changed_at" field.
func (_u *PasswordCredentialUpdateOne) SetLastChangedAt(v time.Time) *PasswordCredentialUpdateOne {
	_u.mutation.SetLastChangedAt(v)
	return _u
}

// SetNillableLastChangedAt sets the "last_changed_at" field if the given value is not nil.
func (_u *PasswordCredentialUpdateOne) SetNillableLastChangedAt(v *time.Time) *PasswordCredentialUpdateOne {
	if v != nil {
		_u.SetLastChangedAt(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PasswordCredentialUpdateOne) SetUser(v *User) *PasswordCredentialUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PasswordCredentialMutation object of the builder.
func (_u *PasswordCredentialUpdateOne) Mutation() *PasswordCredentialMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PasswordCredentialUpdateOne) ClearUser() *PasswordCredentialUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PasswordCredentialUpdate builder.
func (_u *PasswordCredentialUpdateOne) Where(ps ...predicate.PasswordCredential) *PasswordCredentialUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PasswordCredentialUpdateOne) Select(field string, fields ...string) *PasswordCredentialUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PasswordCredential entity.
func (_u *PasswordCredentialUpdateOne) Save(ctx context.Context) (*PasswordCredential, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PasswordCredentialUpdateOne) SaveX(ctx context.Context) *PasswordCredential {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PasswordCredentialUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PasswordCredentialUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *PasswordCredentialUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := passwordcredential.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PasswordCredentialUpdateOne) check() error {
	if v, ok := _u.mutation.PasswordHash(); ok {
		if err := passwordcredential.PasswordHashValidator(v); err != nil {
			return &ValidationError{Name: "password_hash", err: fmt.Errorf(`ent: validator failed for field "PasswordCredential.password_hash": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PasswordCredential.user"`)
	}
	return nil
}

func (_u *PasswordCredentialUpdateOne) sqlSave(ctx context.Context) (_node *PasswordCredential, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(passwordcredential.Table, passwordcredential.Columns, sqlgraph.NewFieldSpec(passwordcredential.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PasswordCredential.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, passwordcredential.FieldID)
		for _, f := range fields {
			if !passwordcredential.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != passwordcredential.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PasswordHash(); ok {
		_spec.SetField(passwordcredential.FieldPasswordHash, field.TypeString, value)
	}
	if value, ok := _u.mutation.Algorithm(); ok {
		_spec.SetField(passwordcredential.FieldAlgorithm, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(passwordcredential.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.LastChangedAt(); ok {
		_spec.SetField(passwordcredential.FieldLastChangedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   passwordcredential.UserTable,
			Columns: []string{passwordcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   passwordcredential.UserTable,
			Columns: []string{passwordcredential.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PasswordCredential{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{passwordcredential.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
